### ISSUE TITLE
First complete template

### ISSUE THREAD

**Issue by anh-khue** [Adaption/basis#1]
Create a template with all of necessary pages of a typical e-commerce website.

**Comment by anh-khue** [comment]
![image](https://user-images.githubusercontent.com/28884098/39580710-f5223354-4f13-11e8-8bce-53b9cbfcce5d.png)
@TuanDSE62171 Is this an error or you did this on purpose?

**Comment by TuanDSE62171** [comment]
@anh-khue error fixed, review needed 
commit 930391e
