### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by swomfire** [Adaption/basis#10]
Discussion on how to implement dataset and noSQL into the system

**Comment by anh-khue** [comment]
@duysuper3 the Dataset, or Product's Attributes Set, should we put it in Website Service or Product Service? I need your opinion

**Comment by duysuper3** [comment]
@anh-khue For more convenient querying data, put it in the Product Service.
I don't think we're going to reuse the Attributes Set so there's no advantages of putting it in the Website Service.

However, if we're going to built something like a management page, we'll have to reconsider about it.

**Comment by anh-khue** [comment]
@duy-dpd Ok, so we're going to add new table in product service's database for managing those sets. I'm going to close this issue tonight.
Btw, I will soon create new issue for modifying the product service' database and assign you into it. Please notice for any notifications.
