### ISSUE TITLE
Database for Product Microservice

### ISSUE THREAD

**Issue by anh-khue** [Adaption/basis#2]
Database for Product Microservice with scripted file for structure and sample data. A document is required for specific functionalities of each fields in every table(s).

- [x] Structure Script
- [x] Sample Data Script
- [x] Document

**Comment by anh-khue** [comment]
@duysuper3 Well done, just a little bit to discuss.

1. `product_info` table is a good idea. However, I am considering whether we are going to manage that much of detail or not; those information can be put in field `description` in table `product`. (Let me know if you have any idea. I still think this additional table is a good one, just not so sure
2. `image` table may get conflict with `media` service from @nhat7490 if we do not manage well. We all  3 have to discuss this clearly to make sure which service will manage these images.

**Comment by nhat7490** [comment]
@anh-khue why i didnt get any notification when i get tagged?
