### ISSUE TITLE
Database for Website Microservice

### ISSUE THREAD

**Issue by anh-khue** [Adaption/basis#5]
Database for Website Microservice with scripted file for structure and sample data. A document is required for specific functionalities of each fields in every table(s).

- [x] Structure Script
- [x] Sample Data Script
- [x] Document

**Comment by swomfire** [comment]
Structure Script ?

**Comment by anh-khue** [comment]
@swomfire next time tag me please. 
The structure scripts includes commands for creating tables and relationships between them.
